# intsall the conda environment for DSCI_522 group 7 project: Cervical Cancer Risk Prediction
# the following command to be run in base conda environment:
# conda env create -f environment.yaml
name: 'rfcc'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - scikit-learn>=1.1.3
  - altair
  - altair_saver
  - pandas<1.5
  - docopt
  - pip
  - pip:
    - joblib==1.1.0
    - selenium==4.2.0
    - vl-convert-python
